
public class Collection_Framework_In_JAVA {
	

/*
    COLLECTION FRAMEWORK IS JAVA API WHICH PROVIDES
    ARCHITECTURE TO STORE AND MANIPULATE GROUP OF OBJECTS
    
    
    
    AND THE COLLECTION FRAMEWORK PROVIDE THE IMPLEMENTATION OF THE
    CLASSES THAT THEY HAVE (ALGORITHAM)
    
    
    API -> API STAND FOR  < APPLICATION PROGRAM INTERFACE > WHICH HAVE
           PREDEFINED CLASSES AND INTERFACES
 
   IN HINDI : COLLECTION FRAMEWORK HAME CLASSES OR INTERFACES DETA
              JISKI HELP SE HUM KAHI SAARE OBJECTS KO EK GROUP MAI 
              RAKH SAKTE (COLLECTION M RAKH SAKTE J=HAI)
              OR HUM USS OBJECTS KO MANIPULATE (CHANGE - UPDATE)
              BHI KR SAKTE HAI OPERATION PERFORM KRKE 
              OR COLLECTION HUM OPERATION PROVIDE KRTA KI
              APP ISS TYPE OPERATION ISS OBJECTS PR KR SAKTE HO 
              
              
    
              
  WHERE IS COLLECTION FRAMEWORK IN JAVA ?
  
  IN JAVA.UTIL PACKAGE
  
  IF WE WANT TO USE COLLECTION IN OUR PROGRAM FIRAT WE HAVE TO IMPORT THAT
  
  
  SOME INTERFACE OF COLLECTION FRAMEWORK ->COLLECTION MAP SET LIST QUEUE ETC
  
               
              
            
  
 */
	
	
	
	

}
