
public class What_Is_Collection {

/*
 
 ANY GROUP OF INDIVIDUAL OBJECTS WHICH ARE REPRESNTED
 AS A SINGLE UNIT IS KNOW AS THE COLLECTION OF THE OBJECTS
 
 FOR EXMAPLES :  1.COLLECTION OF DVDS.
                 2.COLLECTION OF STICKERS.
                 3.COLLECTION OF CLOTHS
                 4.COLLECTION OF PENS.
       
                 
IN HINDI : COLLECTION EK TYPE KA GROUP HOTA HAI OBJECTS KA 
(OBJECTS MEANS REAL WORLD ENTITY) OR JISSE WO STORE HOTA H USSE COLLECTION
BOLTE HAI. OR JAB BHI HAMME COLLECTIONS KE OBJECTS KO USE KRNA HOTA HAI 
TOH FIRST HAM COLLECTION KO USE KRTE HAI.

  
SIMPLE :  1.JHOLA MAI SABJI HAI -> YAHA PR JHOLA JO HAI EK COLLECTION KE RUP
                                   (TYPE) M SHOW HORA HAI OR USKE ANDER JO SABJIYA
                                   HAI WO OBJECT HAI US COLLECTION KI.   
                                   
                 
                   
  
  
  
  
  
  
 */
	
	
	
	
	
	
	
	
	
	
	
	
	
	

}
